import type { Locale } from '../i18n/types'
import { uiT } from '../i18n/catalogResolve'
import { HermesNavIcon } from '../components/HermesNavIcon'
import {
  Bot,
  Briefcase,
  Building2,
  Cable,
  ConciergeBell,
  CreditCard,
  FileText,
  FolderArchive,
  Handshake,
  Headset,
  Home,
  LayoutDashboard,
  Image as ImageIcon,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Package,
  PenLine,
  Settings2,
  Sparkles,
  Search,
  Smartphone,
  Users,
  Video,
  Wrench,
  Store,
} from 'lucide-react'
import type { ComponentType } from 'react'

/** Props passed by sidebar / module rows (Lucide-compatible `strokeWidth` ignored). */
export type NavModuleIconProps = { size?: number; strokeWidth?: number; className?: string }

export type ModuleStatus = '已完成' | '进行中' | '待确认'

export interface ModuleRouteMeta {
  id: string
  label: string
  route: string
  icon: ComponentType<NavModuleIconProps>
  status: ModuleStatus
  legacyPath: string
  description: string
  summary: string
}

export interface SidebarSection {
  id: string
  title: string
  items: string[]
}

export const MODULES: Record<string, ModuleRouteMeta> = {
  dashboard: {
    id: 'dashboard',
    label: '仪表盘',
    route: '/workbench',
    icon: LayoutDashboard,
    status: '已完成',
    legacyPath: 'pages/WorkbenchHomePage.tsx',
    description: '账号、通道与资源状态一屏概览',
    summary: '查看智能空间、业务配置、账户资源与伙伴计划状态。',
  },
  newChat: {
    id: 'newChat',
    label: '新对话',
    route: '/workbench/assistant',
    icon: Sparkles,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> QUICK_ACTIONS:new-chat + panels/HeroPanel.vue',
    description: '智能助手新对话入口',
    summary: '直接发起智能助手对话，不选择业务、插件、模式或模型。',
  },
  search: {
    id: 'search',
    label: '搜索',
    route: '/workbench',
    icon: Search,
    status: '进行中',
    legacyPath: 'components/AgentThreadSearchDialog.vue',
    description: '搜索全部主题',
    summary: '搜索最近更新和历史主题，点击后进入对应对话。',
  },
  hero: {
    id: 'hero',
    label: '工作台',
    route: '/workbench/assistant',
    icon: Home,
    status: '进行中',
    legacyPath: 'pages/Workbench.vue + panels/HeroPanel.vue',
    description: '对话导向首页入口',
    summary: '从新对话、搜索、客服和自动化进入工作。',
  },
  consultant: {
    id: 'consultant',
    label: '智能助手',
    route: '/workbench/assistant',
    icon: MessageCircle,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> consultant + panels/AgentPanel.vue',
    description: '通用 AI 智能助手线程入口',
    summary: '已接入线程列表、详情与消息发送。',
  },
  system: {
    id: 'system',
    label: '软件开发',
    route: '/workbench/system',
    icon: Wrench,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> system + panels/AgentPanel.vue',
    description: '软件开发业务线程入口',
    summary: '复用 general 域线程，按“软件开发”入口进入对话。',
  },
  marketing: {
    id: 'marketing',
    label: '推广能力',
    route: '/workbench/marketing',
    icon: Megaphone,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> marketing + panels/AgentPanel.vue',
    description: '营销业务线程入口',
    summary: '已按营销域接入线程列表与会话详情。',
  },
  marketingImage: {
    id: 'marketingImage',
    label: '图片设计',
    route: '/workbench/marketing/image',
    icon: ImageIcon,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> marketing image mode',
    description: '图片素材生成与改图入口',
    summary: '复用 marketing 域，默认进入图片生成模式。',
  },
  marketingVideo: {
    id: 'marketingVideo',
    label: '视频制作',
    route: '/workbench/marketing/video',
    icon: Video,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> marketing video mode',
    description: '短视频脚本与视频生成入口',
    summary: '复用 marketing 域，默认进入视频生成模式。',
  },
  marketingCopy: {
    id: 'marketingCopy',
    label: '文案生成',
    route: '/workbench/marketing/copy',
    icon: PenLine,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> marketing text mode',
    description: '营销文案、选题与发布内容入口',
    summary: '复用 marketing 域，默认进入文字文案模式。',
  },
  kefu: {
    id: 'kefu',
    label: '客服',
    route: '/workbench/kefu',
    icon: Headset,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> kefu + panels/kefu/KefuRouter.vue',
    description: '客户咨询、店铺、AI 问答库、快捷回复和技术配置',
    summary: '按等待中、进行中、已归档、客服设置和帮助中心切换。',
  },
  stores: {
    id: 'stores',
    label: '店铺管理',
    route: '/workbench/kefu/settings?tab=stores',
    icon: Building2,
    status: '已完成',
    legacyPath: 'panels/kefu/StoresPanel.vue',
    description: '多店铺设置与接入配置',
    summary: '管理店铺资料、启用状态和接入信息。',
  },
  qaTemplates: {
    id: 'qaTemplates',
    label: '客服资料',
    route: '/workbench/kefu/settings?tab=uploads',
    icon: MessageCircle,
    status: '进行中',
    legacyPath: 'panels/kefu/QaTemplatesPanel.vue + CorpusPanel.vue',
    description: '资料来源 / AI 问答条目 / 访客快捷问题',
    summary: '统一管理资料来源、AI 问答条目、访客快捷问题与生成问答。',
  },
  techConfig: {
    id: 'techConfig',
    label: '技术配置',
    route: '/workbench/kefu/settings?tab=tech-config',
    icon: Cable,
    status: '进行中',
    legacyPath: 'panels/kefu/TechConfigPanel.vue',
    description: '渠道、SDK、API 接入配置',
    summary: '管理渠道接入、SDK 嵌码、API 凭据和调用说明。',
  },
  liveChat: {
    id: 'liveChat',
    label: '客户咨询',
    route: '/workbench/live-chat',
    icon: MessagesSquare,
    status: '进行中',
    legacyPath: 'panels/kefu/LiveChatPanel.vue + store/liveChat.ts',
    description: '会话列表 + 会话区 + 输入区',
    summary: '处理等待中、进行中和已归档会话，支持接管、AI 建议回复、快速回答和人工发送。',
  },
  support: {
    id: 'support',
    label: '辣鸡PPT',
    route: '/workbench/support',
    icon: ConciergeBell,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> support + panels/AgentPanel.vue',
    description: '支持业务线程入口',
    summary: '已按 support 域接入线程对话主流程。',
  },
  agency: {
    id: 'agency',
    label: '企业服务',
    route: '/workbench/agency',
    icon: Handshake,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> agency + panels/AgentPanel.vue',
    description: '商务代理业务线程入口',
    summary: '已按 agency 域接入线程对话主流程。',
  },
  automation: {
    id: 'automation',
    label: '自动化',
    route: '/workbench/automation',
    icon: Bot,
    status: '进行中',
    legacyPath: 'panels/AutomationPanel.vue',
    description: '模板和任务',
    summary: '选择自动化模板，发起任务，并查看最近任务记录。',
  },
  socialPosting: {
    id: 'socialPosting',
    label: '社交发帖',
    route: '/workbench/automation/social',
    icon: Bot,
    status: '进行中',
    legacyPath: 'pages/SocialPostingPage.tsx',
    description: '多平台素材包与发帖',
    summary: '通过 Ayrshare 绑定社交账号，创建素材包并立即或定时发布到多个平台。',
  },
  repository: {
    id: 'repository',
    label: '市场',
    route: '/workbench/repository',
    icon: Package,
    status: '进行中',
    legacyPath: 'panels/AutomationRepositoryPanel.vue',
    description: '跨境电商和上架服务市场',
    summary: '按跨境电商、app 上架、小程序上架和备案切换服务市场。',
  },
  fileLibrary: {
    id: 'fileLibrary',
    label: '文件库',
    route: '/workbench/file-library',
    icon: FileText,
    status: '进行中',
    legacyPath: 'panels/AutomationFileLibraryPanel.vue',
    description: '上传与 AI 梳理文件',
    summary: '上传文件，选择资料，生成 Markdown，下载或分享结果。',
  },
  feedback: {
    id: 'feedback',
    label: '帮助中心',
    route: '/workbench/feedback',
    icon: Wrench,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> feedback + panels/AgentPanel.vue',
    description: '缺陷、需求、咨询和投诉争议',
    summary: '已按 feedback 域接入线程对话主流程。',
  },
  account: {
    id: 'account',
    label: '账户中心',
    route: '/workbench/account',
    icon: Settings2,
    status: '已完成',
    legacyPath: 'panels/account/AccountPanel.vue + BillingPanel.vue + WalletPanel.vue + UsagePanel.vue',
    description: '账户、钱包、账单、用量入口',
    summary: '钱包、计费、用量分区已可用。',
  },
  teamManagement: {
    id: 'teamManagement',
    label: '团队管理',
    route: '/workbench/team-management',
    icon: Users,
    status: '进行中',
    legacyPath: 'panels/team/TeamManagementPanel.vue',
    description: '团队成员与接待配置入口',
    summary: '已提供成员列表、添加与角色接待配置。',
  },
  archives: {
    id: 'archives',
    label: '历史会话',
    route: '/workbench/archives',
    icon: FolderArchive,
    status: '进行中',
    legacyPath: 'panels/AgentArchivesPanel.vue',
    description: 'Agent 历史归档入口',
    summary: '已提供归档列表与恢复动作。',
  },
  generationAssets: {
    id: 'generationAssets',
    label: '仓库',
    route: '/workbench/generation-assets',
    icon: Briefcase,
    status: '进行中',
    legacyPath: 'panels/GenerationAssetsPanel.vue',
    description: '用户空间素材仓库',
    summary: '汇总图片、视频、PPT 和文件等生成素材。',
  },
  hermesPanel: {
    id: 'hermesPanel',
    label: 'hermes',
    route: '/workbench/hermes',
    icon: HermesNavIcon,
    status: '进行中',
    legacyPath: 'new: Hermes operation panel',
    description: 'Hermes 技术操作面板',
    summary: '从左侧仓库下方入口确认风险后进入右侧内容面板。',
  },
  usPhoneNumbers: {
    id: 'usPhoneNumbers',
    label: '号码',
    route: '/workbench/generation-assets?tab=numbers',
    icon: Smartphone,
    status: '进行中',
    legacyPath: 'new: billing us-phone numbers',
    description: '美国号码与短信收件箱',
    summary: '开通美国号码，左侧管理号码，右侧查看详情与短信。',
  },
  dcpayCards: {
    id: 'dcpayCards',
    label: '支付卡',
    route: '/workbench/generation-assets?tab=ad-card',
    icon: CreditCard,
    status: '进行中',
    legacyPath: 'new: billing dcpay-card',
    description: '支付卡子账户、开卡与卡充值',
    summary: '用平台点充值支付卡子账户，再开卡、卡充值并查看流水。',
  },
  standaloneSite: {
    id: 'standaloneSite',
    label: '独立站',
    route: '/workbench/standalone-site',
    icon: Store,
    status: '进行中',
    legacyPath: 'pages/StandaloneSitePortalPage.tsx',
    description: '独立站用户端与后台管理入口',
    summary: '管理独立站配置，打开用户端 storefront 或后台管理。',
  },
  skills: {
    id: 'skills',
    label: '技能',
    route: '/workbench/skills',
    icon: Package,
    status: '已完成',
    legacyPath: 'panels/SkillsPanel.vue',
    description: '技能安装与绑定入口',
    summary: '支持技能安装、卸载与业务入口自动加载绑定。',
  },
}

export const SIDEBAR_SECTIONS: SidebarSection[] = [
  { id: 'quick', title: '快捷入口', items: ['dashboard', 'kefu', 'automation', 'socialPosting', 'repository', 'generationAssets', 'standaloneSite'] },
  { id: 'business', title: '智能工作台', items: ['consultant', 'system', 'marketingImage', 'marketingVideo', 'marketingCopy', 'support', 'agency', 'feedback'] },
]

const MODULE_I18N: Partial<Record<string, { label?: string; desc?: string; summary?: string }>> = {
  dashboard: { label: 'common.module.dashboard.label', desc: 'common.module.dashboard.desc', summary: 'common.module.dashboard.summary' },
  newChat: { label: 'common.module.newChat.label', desc: 'common.module.newChat.desc', summary: 'common.module.newChat.summary' },
  search: { label: 'common.module.search.label', desc: 'common.module.search.desc', summary: 'common.module.search.summary' },
  hero: { label: 'common.module.hero.label', desc: 'common.module.hero.desc', summary: 'common.module.hero.summary' },
  consultant: { desc: 'common.module.consultant.desc', summary: 'common.module.consultant.summary' },
  system: { label: 'common.nav.software', desc: 'common.module.system.desc', summary: 'common.module.system.summary' },
  marketing: { label: 'common.nav.marketing', desc: 'common.module.marketing.desc', summary: 'common.module.marketing.summary' },
  marketingImage: { label: 'common.nav.marketingImage', desc: 'common.module.marketingImage.desc', summary: 'common.module.marketingImage.summary' },
  marketingVideo: { label: 'common.nav.marketingVideo', desc: 'common.module.marketingVideo.desc', summary: 'common.module.marketingVideo.summary' },
  marketingCopy: { label: 'common.nav.marketingCopy', desc: 'common.module.marketingCopy.desc', summary: 'common.module.marketingCopy.summary' },
  kefu: { label: 'common.nav.kefu', desc: 'common.module.kefu.desc', summary: 'common.module.kefu.summary' },
  stores: { label: 'common.module.kefuStores.label', desc: 'common.module.kefuStores.desc', summary: 'common.module.kefuStores.summary' },
  qaTemplates: { label: 'common.nav.kefu.qaTemplates', desc: 'common.module.kefuProfile.desc', summary: 'common.module.kefuProfile.summary' },
  techConfig: { label: 'common.nav.kefu.techConfig', desc: 'common.module.kefuTech.desc', summary: 'common.module.kefuTech.summary' },
  liveChat: { label: 'common.module.liveChat.label', desc: 'common.module.liveChat.desc', summary: 'common.module.liveChat.summary' },
  support: { label: 'common.nav.support', desc: 'common.module.support.desc', summary: 'common.module.support.summary' },
  agency: { label: 'common.nav.agency', desc: 'common.module.agency.desc', summary: 'common.module.agency.summary' },
  automation: { label: 'common.nav.automation', desc: 'common.module.automation.desc', summary: 'common.module.automation.summary' },
  socialPosting: { label: 'common.module.socialPosting.label', desc: 'common.module.socialPosting.desc', summary: 'common.module.socialPosting.summary' },
  repository: { label: 'common.module.repository.label', desc: 'common.module.repository.desc', summary: 'common.module.repository.summary' },
  fileLibrary: { label: 'common.module.fileLibrary.label', desc: 'common.module.fileLibrary.desc', summary: 'common.module.fileLibrary.summary' },
  feedback: { label: 'common.nav.feedback', desc: 'common.module.feedback.desc', summary: 'common.module.feedback.summary' },
  account: { label: 'common.module.account.label', desc: 'common.module.account.desc', summary: 'common.module.account.summary' },
  teamManagement: { label: 'common.module.team.label', desc: 'common.module.team.desc', summary: 'common.module.team.summary' },
  archives: { label: 'common.module.archives.label', desc: 'common.module.archives.desc', summary: 'common.module.archives.summary' },
  generationAssets: { label: 'common.module.generationAssets.label', desc: 'common.module.generationAssets.desc', summary: 'common.module.generationAssets.summary' },
  standaloneSite: { label: 'common.module.standaloneSite.label', desc: 'common.module.standaloneSite.desc', summary: 'common.module.standaloneSite.summary' },
  hermesPanel: { desc: 'common.module.hermes.desc', summary: 'common.module.hermes.summary' },
  usPhoneNumbers: { label: 'common.module.usPhone.label', desc: 'common.module.usPhone.desc', summary: 'common.module.usPhone.summary' },
  dcpayCards: { label: 'common.module.dcpay.label', desc: 'common.module.dcpay.desc', summary: 'common.module.dcpay.summary' },
  skills: { label: 'common.module.skills.label', desc: 'common.module.skills.desc', summary: 'common.module.skills.summary' },
}

const MODULE_STATUS_KEYS: Record<ModuleStatus, string> = {
  '已完成': 'common.module.status.done',
  '进行中': 'common.module.status.inProgress',
  '待确认': 'common.module.status.pending',
}

const SIDEBAR_SECTION_KEYS: Record<string, string> = {
  quick: 'common.module.section.quick',
  business: 'common.module.section.business',
  consultant: 'common.nav.consultant',
}

export function getModuleRegistryLabels(locale: Locale) {
  const modules = Object.fromEntries(
    Object.entries(MODULES).map(([id, mod]) => {
      const keys = MODULE_I18N[id]
      return [id, {
        ...mod,
        label: keys?.label ? uiT(locale, keys.label, mod.label) : mod.label,
        description: keys?.desc ? uiT(locale, keys.desc, mod.description) : mod.description,
        summary: keys?.summary ? uiT(locale, keys.summary, mod.summary) : mod.summary,
        status: uiT(locale, MODULE_STATUS_KEYS[mod.status], mod.status) as ModuleStatus,
      }]
    }),
  ) as Record<string, ModuleRouteMeta>

  const sidebarSections = SIDEBAR_SECTIONS.map(section => ({
    ...section,
    title: uiT(locale, SIDEBAR_SECTION_KEYS[section.id] || section.title, section.title),
  }))

  return { modules, sidebarSections }
}

export const TOPBAR_TRACKED_ROUTE_IDS = new Set<string>([
  'dashboard',
  'hero',
  'newChat',
  'search',
  'liveChat',
  'skills',
  'consultant',
  'system',
  'marketing',
  'marketingImage',
  'marketingVideo',
  'marketingCopy',
  'kefu',
  'stores',
  'qaTemplates',
  'techConfig',
  'support',
  'agency',
  'automation',
  'socialPosting',
  'repository',
  'fileLibrary',
  'feedback',
  'account',
  'teamManagement',
  'archives',
  'generationAssets',
  'standaloneSite',
  'hermesPanel',
  'usPhoneNumbers',
  'dcpayCards',
])
