import {
  Bot,
  Briefcase,
  Building2,
  Cable,
  ConciergeBell,
  FileText,
  FolderArchive,
  Handshake,
  Headset,
  Home,
  Megaphone,
  MessageCircle,
  MessagesSquare,
  Package,
  Settings2,
  Sparkles,
  Search,
  Users,
  Wrench,
} from 'lucide-react'
import type { ComponentType } from 'react'

/** Props passed by sidebar / module rows (Lucide-compatible `strokeWidth` ignored). */
export type NavModuleIconProps = { size?: number; strokeWidth?: number; className?: string }

export type ModuleStatus = '已完成' | '进行中' | '待确认'

export interface ModuleRouteMeta {
  id: string
  label: string
  route: string
  icon: ComponentType<NavModuleIconProps>
  status: ModuleStatus
  legacyPath: string
  description: string
  summary: string
}

export interface SidebarSection {
  id: string
  title: string
  items: string[]
}

export const MODULES: Record<string, ModuleRouteMeta> = {
  newChat: {
    id: 'newChat',
    label: '新对话',
    route: '/workbench',
    icon: Sparkles,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> QUICK_ACTIONS:new-chat + panels/HeroPanel.vue',
    description: '选择业务后开始新主题',
    summary: '进入新对话 Hero，先选业务，再发送给对应智能角色。',
  },
  search: {
    id: 'search',
    label: '搜索',
    route: '/workbench',
    icon: Search,
    status: '进行中',
    legacyPath: 'components/AgentThreadSearchDialog.vue',
    description: '搜索全部主题',
    summary: '搜索最近更新和历史主题，点击后进入对应对话。',
  },
  hero: {
    id: 'hero',
    label: '工作台',
    route: '/workbench',
    icon: Home,
    status: '进行中',
    legacyPath: 'pages/Workbench.vue + panels/HeroPanel.vue',
    description: '对话导向首页入口',
    summary: '从新对话、搜索、客服、自动化和文件库进入工作。',
  },
  consultant: {
    id: 'consultant',
    label: '顾问',
    route: '/workbench/consultant',
    icon: MessageCircle,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> consultant + panels/AgentPanel.vue',
    description: '通用 AI 顾问线程入口',
    summary: '已接入线程列表、详情与消息发送。',
  },
  system: {
    id: 'system',
    label: '程序员',
    route: '/workbench/system',
    icon: Wrench,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> system + panels/AgentPanel.vue',
    description: '程序员业务线程入口',
    summary: '复用 general 域线程，按“程序员”入口进入对话。',
  },
  marketing: {
    id: 'marketing',
    label: '推广大师',
    route: '/workbench/marketing',
    icon: Megaphone,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> marketing + panels/AgentPanel.vue',
    description: '营销业务线程入口',
    summary: '已按营销域接入线程列表与会话详情。',
  },
  kefu: {
    id: 'kefu',
    label: '客服',
    route: '/workbench/kefu',
    icon: Headset,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> kefu + panels/kefu/KefuRouter.vue',
    description: '客户咨询、店铺、问答模板和技术配置',
    summary: '按客户咨询、店铺、问答模板、技术配置四个标签切换。',
  },
  stores: {
    id: 'stores',
    label: '店铺',
    route: '/workbench/kefu/stores',
    icon: Building2,
    status: '已完成',
    legacyPath: 'panels/kefu/StoresPanel.vue',
    description: '多店铺设置与接入配置',
    summary: '管理店铺资料、启用状态和接入信息。',
  },
  qaTemplates: {
    id: 'qaTemplates',
    label: '问答模板',
    route: '/workbench/kefu/qa-templates',
    icon: MessageCircle,
    status: '进行中',
    legacyPath: 'panels/kefu/QaTemplatesPanel.vue + CorpusPanel.vue',
    description: '资料来源 / 问答条目 / 生成问答',
    summary: '统一管理资料来源、问答条目、生成问答与建议回复。',
  },
  techConfig: {
    id: 'techConfig',
    label: '技术配置',
    route: '/workbench/kefu/tech-config',
    icon: Cable,
    status: '进行中',
    legacyPath: 'panels/kefu/TechConfigPanel.vue',
    description: '渠道、SDK、API 接入配置',
    summary: '管理渠道接入、SDK 嵌码、API 凭据和调用说明。',
  },
  liveChat: {
    id: 'liveChat',
    label: '客户咨询',
    route: '/workbench/live-chat',
    icon: MessagesSquare,
    status: '进行中',
    legacyPath: 'panels/kefu/LiveChatPanel.vue + store/liveChat.ts',
    description: '会话列表 + 会话区 + 输入区',
    summary: '处理等待中、进行中和已归档会话，支持接管、建议回复和人工发送。',
  },
  support: {
    id: 'support',
    label: '渠道专员',
    route: '/workbench/support',
    icon: ConciergeBell,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> support + panels/AgentPanel.vue',
    description: '支持业务线程入口',
    summary: '已按 support 域接入线程对话主流程。',
  },
  agency: {
    id: 'agency',
    label: '商务经理',
    route: '/workbench/agency',
    icon: Handshake,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> agency + panels/AgentPanel.vue',
    description: '商务代理业务线程入口',
    summary: '已按 agency 域接入线程对话主流程。',
  },
  automation: {
    id: 'automation',
    label: '自动化',
    route: '/workbench/automation',
    icon: Bot,
    status: '进行中',
    legacyPath: 'panels/AutomationPanel.vue',
    description: '模板和任务',
    summary: '选择自动化模板，发起任务，并查看最近任务记录。',
  },
  fileLibrary: {
    id: 'fileLibrary',
    label: '文件库',
    route: '/workbench/file-library',
    icon: FileText,
    status: '进行中',
    legacyPath: 'panels/AutomationFileLibraryPanel.vue',
    description: '上传与 AI 梳理文件',
    summary: '上传文件，选择资料，生成 Markdown，下载或分享结果。',
  },
  feedback: {
    id: 'feedback',
    label: '维修工',
    route: '/workbench/feedback',
    icon: Wrench,
    status: '进行中',
    legacyPath: 'lib/nav.ts -> feedback + panels/AgentPanel.vue',
    description: '缺陷、需求、咨询和投诉争议',
    summary: '已按 feedback 域接入线程对话主流程。',
  },
  account: {
    id: 'account',
    label: '账户中心',
    route: '/workbench/account',
    icon: Settings2,
    status: '已完成',
    legacyPath: 'panels/account/AccountPanel.vue + BillingPanel.vue + WalletPanel.vue + UsagePanel.vue',
    description: '账户、钱包、账单、用量入口',
    summary: '钱包、计费、用量分区已可用。',
  },
  teamManagement: {
    id: 'teamManagement',
    label: '团队管理',
    route: '/workbench/team-management',
    icon: Users,
    status: '进行中',
    legacyPath: 'panels/team/TeamManagementPanel.vue',
    description: '团队成员与接待配置入口',
    summary: '已提供成员列表、邀请与角色接待配置。',
  },
  archives: {
    id: 'archives',
    label: '历史会话',
    route: '/workbench/archives',
    icon: FolderArchive,
    status: '进行中',
    legacyPath: 'panels/AgentArchivesPanel.vue',
    description: 'Agent 历史归档入口',
    summary: '已提供归档列表与恢复动作。',
  },
  generationAssets: {
    id: 'generationAssets',
    label: '生成资产',
    route: '/workbench/generation-assets',
    icon: Briefcase,
    status: '进行中',
    legacyPath: 'panels/GenerationAssetsPanel.vue',
    description: '图片/视频任务资产入口',
    summary: '已提供生成任务列表与状态展示。',
  },
  teamChat: {
    id: 'teamChat',
    label: '团队沟通',
    route: '/workbench/team-chat',
    icon: MessagesSquare,
    status: '进行中',
    legacyPath: 'store/teamChat.ts + lib/teamRuntimes.ts + TeamChatRouter',
    description: '团队私聊/群聊入口',
    summary: '已提供会话与私聊入口，实时能力仍待补齐。',
  },
  platformTeam: {
    id: 'platformTeam',
    label: '平台团队沟通',
    route: '/workbench/platform-team',
    icon: Users,
    status: '待确认',
    legacyPath: 'workspace.ts:view=platform-team + TopHeader.vue 提权入口',
    description: '平台侧内部沟通入口',
    summary: '平台管理员可从这里进入平台团队协作空间。',
  },
  skills: {
    id: 'skills',
    label: '技能',
    route: '/workbench/skills',
    icon: Package,
    status: '已完成',
    legacyPath: 'panels/SkillsPanel.vue',
    description: '技能安装与绑定入口',
    summary: '支持技能安装、卸载与业务入口自动加载绑定。',
  },
}

export const SIDEBAR_SECTIONS: SidebarSection[] = [
  { id: 'quick', title: '快捷入口', items: ['newChat', 'search', 'kefu', 'automation', 'fileLibrary'] },
  { id: 'business', title: '智能团队', items: ['system', 'marketing', 'support', 'agency', 'feedback'] },
  { id: 'consultant', title: '顾问', items: ['consultant'] },
]

export const TOPBAR_TRACKED_ROUTE_IDS = new Set<string>([
  'hero',
  'newChat',
  'search',
  'liveChat',
  'skills',
  'consultant',
  'system',
  'marketing',
  'kefu',
  'stores',
  'qaTemplates',
  'techConfig',
  'support',
  'agency',
  'automation',
  'fileLibrary',
  'feedback',
  'account',
  'teamManagement',
  'archives',
  'generationAssets',
  'teamChat',
  'platformTeam',
])
