import { motion } from "motion/react";
import { AlertTriangle, Building2, Clock, FileText, Flag, Mail, MapPin, Phone, Send, ShieldCheck } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router";
import { useSitePreferences, type LocalizedCopy } from "../sitePreferences";

type LegalPageKind = "privacy" | "terms" | "refund" | "contact" | "compliance";

type LegalSection = {
  id?: string;
  title: LocalizedCopy;
  items: LocalizedCopy[];
};

const supportEmail = "support@xiaoone.cn";
const complianceEmail = "compliance@xiaoone.cn";
const supportPhone = "17307404063";

const companyInfo: Array<[LocalizedCopy, LocalizedCopy]> = [
  [{ zh: "运营主体", en: "Operator" }, { zh: "玄水科技（深圳）有限公司", en: "Xuanshui Technology (Shenzhen) Co., Ltd" }],
  [{ zh: "统一社会信用代码", en: "Unified social credit code" }, { zh: "91440300MAKDBL7D3W", en: "91440300MAKDBL7D3W" }],
  [{ zh: "注册地址", en: "Registered address" }, { zh: "深圳市龙华区龙华街道清华社区和平路33号盛龙时代广场B座1420", en: "Room 1420, Block B, Shenglong Times Plaza, Longhua, Shenzhen" }],
  [{ zh: "ICP备案", en: "ICP filing" }, { zh: "粤ICP备2026061441号", en: "粤ICP备2026061441号" }],
];

const legalPages: Record<Exclude<LegalPageKind, "contact" | "compliance">, {
  eyebrow: LocalizedCopy;
  title: LocalizedCopy;
  summary: LocalizedCopy;
  sections: LegalSection[];
}> = {
  privacy: {
    eyebrow: { zh: "隐私政策", en: "Privacy Policy" },
    title: { zh: "xiaoone 官网隐私政策", en: "xiaoone Website Privacy Policy" },
    summary: {
      zh: "本政策适用于官网访问、咨询、联系、购买套餐、在线客服及官网侧数据处理",
      en: "This policy applies to website visits, inquiries, contact forms, plan purchases, online support, and data processing on the xiaoone website",
    },
    sections: [
      {
        title: { zh: "1. 我们是谁", en: "1. Who we are" },
        items: [
          { zh: "xiaoone 官网由玄水科技（深圳）有限公司运营", en: "The xiaoone website is operated by Xuanshui Technology (Shenzhen) Co., Ltd" },
          { zh: "本政策仅覆盖官网侧数据处理，不适用于另行登录的智能工作站、其他产品或第三方服务", en: "This policy covers website-side processing only and does not apply to separate workspaces, other products, or third-party services" },
        ],
      },
      {
        title: { zh: "2. 我们收集的信息", en: "2. Information we collect" },
        items: [
          { zh: "您通过表单、在线客服、邮件或电话提交的姓名、邮箱、电话、公司名称、需求描述和购买咨询内容", en: "Name, email, phone number, company name, requirements, and purchase inquiries you submit through forms, support, email, or phone" },
          { zh: "官网访问日志、设备信息、浏览器信息、页面路径、错误日志和安全记录", en: "Website logs, device details, browser details, page paths, error logs, and security records" },
          { zh: "Cookie 和类似技术产生的语言、主题、访问安全和基础统计偏好", en: "Language, theme, security, and basic analytics preferences generated by cookies or similar technologies" },
          { zh: "套餐、订单、付款、发票、对账、客服沟通和售后处理所需信息", en: "Plan, order, payment, invoice, reconciliation, support conversation, and after-sales information" },
          { zh: "如官网提供 AI 辅助咨询，我们可能处理您主动输入的内容，用于生成回复建议、识别需求类型或分配人工跟进", en: "If AI assistance is provided, we may process the content you enter to draft replies, identify request types, or route staff follow-up" },
        ],
      },
      {
        title: { zh: "3. 我们如何使用信息", en: "3. How we use information" },
        items: [
          { zh: "响应咨询、处理购买需求、完成交易、安排售后支持和隐私数据请求", en: "To respond to inquiries, process purchase requests, complete transactions, arrange support, and handle privacy requests" },
          { zh: "展示官网内容、套餐信息、支付确认页和相关服务说明", en: "To present website content, plan information, payment confirmation pages, and service descriptions" },
          { zh: "排查官网故障、保障系统安全、防止异常访问和滥用行为", en: "To troubleshoot the site, protect system security, and prevent abnormal access or abuse" },
          { zh: "改进官网页面、内容表达、客服流程和服务体验", en: "To improve page experience, content clarity, support workflows, and service quality" },
        ],
      },
      {
        title: { zh: "4. 委托处理、共享、转让和公开披露", en: "4. Processing, sharing, transfer, and disclosure" },
        items: [
          { zh: "我们可能委托云服务、邮件、短信、支付、客服、统计分析和安全服务商处理必要信息", en: "We may use cloud, email, SMS, payment, support, analytics, and security providers to process necessary information" },
          { zh: "我们不会出售您的个人信息，也不会将其用于与官网服务无关的营销用途，除非取得明确同意或法律另有规定", en: "We do not sell personal information or use it for unrelated marketing unless you consent or the law requires otherwise" },
          { zh: "如发生合并、分立、资产转让或类似交易，我们会要求新的接收方继续受本政策约束", en: "If merger, division, asset transfer, or similar transactions occur, the recipient will be required to follow this policy" },
          { zh: "法律法规、监管要求、司法机关或保护用户及系统安全所必需时，我们可能依法披露必要信息", en: "We may disclose necessary information when required by law, regulators, courts, or to protect users and system security" },
        ],
      },
      {
        title: { zh: "5. 保存、安全、权利和未成年人保护", en: "5. Retention, security, rights, and minors" },
        items: [
          { zh: "我们仅在实现处理目的、履行合同、解决争议和遵守法律所需期限内保存信息", en: "We retain information only as long as needed for processing purposes, contracts, disputes, and legal compliance" },
          { zh: "我们采取访问控制、日志审计、加密传输、权限隔离和最小必要原则保护信息", en: "We use access control, log auditing, encrypted transmission, permission isolation, and data minimization" },
          { zh: "您可以通过 support@xiaoone.cn 请求查询、更正、删除、复制或撤回同意", en: "You can contact support@xiaoone.cn to request access, correction, deletion, copy, or withdrawal of consent" },
          { zh: "官网及服务主要面向企业、商户及具备完全民事行为能力的成年人。未满 18 周岁的用户不得注册、购买或提交业务资料；如我们发现相关信息涉及未成年人，将依法删除或在必要情况下取得监护人同意", en: "The site and services are intended for businesses, merchants, and adults with full civil capacity. Users under 18 may not register, purchase, or submit business materials; if we discover minor-related information, we will delete it or obtain guardian consent where legally required" },
        ],
      },
      {
        title: { zh: "6. 第三方服务、个人信息提供、政策更新和联系", en: "6. Third parties, personal information provision, updates, and contact" },
        items: [
          { zh: "官网可能包含第三方支付、客服、邮件、地图、统计或外部链接，第三方服务适用其自身规则", en: "The site may include third-party payment, support, email, maps, analytics, or external links governed by their own rules" },
          { zh: "官网原则上在中华人民共和国境内处理个人信息。若未来确因业务需要向境外提供个人信息，我们将依法履行告知、单独同意、个人信息保护影响评估及适用的安全评估、认证或标准合同等程序", en: "The website generally processes personal information within mainland China. If future business needs require providing personal information overseas, we will complete legally required notice, separate consent, impact assessment, and applicable security assessment, certification, or standard-contract procedures" },
          { zh: "本政策可能根据官网功能、服务内容、法律法规或业务调整更新，更新后在官网展示", en: "This policy may be updated for feature, service, legal, or business changes and will be shown on the website" },
          { zh: "如对本政策或个人信息处理有问题，请联系 support@xiaoone.cn", en: "For questions about this policy or personal information processing, contact support@xiaoone.cn" },
        ],
      },
    ],
  },
  terms: {
    eyebrow: { zh: "用户协议", en: "User Agreement" },
    title: { zh: "xiaoone 用户协议", en: "xiaoone User Agreement" },
    summary: {
      zh: "本条款适用于官网访问、咨询、套餐购买、支付确认、在线客服及 XiaoOne 智能工作站订阅服务",
      en: "These terms apply to website access, inquiries, plan purchases, payment confirmation, online support, and XiaoOne workspace subscriptions",
    },
    sections: [
      {
        title: { zh: "1. 服务主体和范围", en: "1. Service provider and scope" },
        items: [
          { zh: "本服务由玄水科技（深圳）有限公司提供", en: "The service is provided by Xuanshui Technology (Shenzhen) Co., Ltd" },
          { zh: "官网用于展示智能客服、商业协同、智能工作站、套餐信息、购买咨询、支付确认、售后支持及相关说明", en: "The website presents support, business collaboration, workspace, plan, purchase, payment, and after-sales information" },
          { zh: "具体功能、套餐权益、服务范围、开通方式、计费方式和售后规则，以官网页面、订单、合同、支付确认页、平台后台或双方另行确认的信息为准", en: "Exact features, plan benefits, service scope, activation, billing, and after-sales rules are subject to website pages, orders, contracts, payment confirmation, platform records, or mutual confirmation" },
        ],
      },
      {
        title: { zh: "2. 账号、套餐、购买和交付", en: "2. Accounts, plans, purchase, and delivery" },
        items: [
          { zh: "官网当前展示 personal（娱乐版）、startup（创业版）、business（商户版）三档套餐，价格和权益以页面和订单为准", en: "The website currently provides three plans: Lite, Pro, and Ultra. Prices and benefits follow the page and order" },
          { zh: "可在线购买的套餐应通过价格页进入用户端开通流程，按所选时长与折扣结算", en: "Online plans should enter user-portal activation from the pricing page and settle by selected term and discount" },
          { zh: "第三方渠道或人工服务能力，可能需要商务或客服人工确认后开通", en: "Third-party channels or manual services may require business or support confirmation before activation" },
          { zh: "在未明确展示自动续费并取得授权前，官网套餐不应默认自动续费", en: "Plans should not auto-renew unless auto-renewal is clearly shown and authorized" },
        ],
      },
      {
        title: { zh: "3. 用户提交内容和禁止行为", en: "3. User content and prohibited behavior" },
        items: [
          { zh: "您提交资料、问题、需求、文本、图片、链接或业务信息时，应保证真实、合法、有效", en: "Submitted materials, questions, requirements, text, images, links, or business information must be true, lawful, and valid" },
          { zh: "不得提交违法、侵权、欺诈、恶意营销、垃圾信息、色情、暴力、赌博、危害系统安全或侵犯他人权益的内容", en: "Do not submit illegal, infringing, fraudulent, spam, sexual, violent, gambling, system-harmful, or rights-violating content" },
          { zh: "不得未经授权访问、探测、干扰、破坏官网、服务器、接口或系统", en: "Do not access, probe, interfere with, or damage the website, servers, APIs, or systems without authorization" },
          { zh: "不得未经许可复制、抓取、反向工程、出售、出租或转授权官网内容和服务能力", en: "Do not copy, scrape, reverse engineer, sell, rent, or sublicense website content or service capabilities without permission" },
        ],
      },
      {
        title: { zh: "4. AI 辅助能力边界", en: "4. AI assistance boundaries" },
        items: [
          { zh: "AI 输出仅作为参考，不构成法律、财务、税务、医疗、投资、合规审查或其他专业意见", en: "AI output is for reference only and is not legal, financial, tax, medical, investment, compliance, or other professional advice" },
          { zh: "官网展示的 AI 能力不代表所有场景均已自动开通，也不代表无人值守或无人审核执行", en: "AI capabilities shown on the website do not mean all scenarios are automatically enabled or executed without review" },
          { zh: "涉及合同、付款、退款、资质、税务、报关、金融、医疗、法律或重要业务决策时，应以人工确认和正式文件为准", en: "Contracts, payments, refunds, qualifications, tax, customs, finance, medical, legal, or key business decisions require human confirmation and official documents" },
        ],
      },
      {
        title: { zh: "5. 第三方服务、费用、退款和知识产权", en: "5. Third parties, fees, refunds, and intellectual property" },
        items: [
          { zh: "第三方支付、短信、邮件、云服务、统计、客服、地图、AI 模型、渠道或外部链接适用第三方规则", en: "Third-party payment, SMS, email, cloud, analytics, support, maps, AI models, channels, or external links are governed by third-party rules" },
          { zh: "套餐价格、计费周期、优惠活动、服务权益和支付方式，以官网价格页、支付确认页、订单、合同或平台后台展示为准", en: "Prices, cycles, promotions, benefits, and payment methods follow the pricing page, payment page, order, contract, or platform records" },
          { zh: "退款与售后规则以官网退款与售后说明、支付确认页、订单、合同或双方另行确认的信息为准", en: "Refund and after-sales rules follow the Refund Policy, payment confirmation, order, contract, or other confirmed information" },
          { zh: "官网中的品牌、logo、界面、文案、图形、代码、页面结构、产品名称和服务说明归玄水科技（深圳）有限公司或合法权利人所有", en: "Brand, logos, UI, copy, graphics, code, page structure, product names, and service descriptions belong to Xuanshui Technology (Shenzhen) Co., Ltd or rights holders" },
        ],
      },
      {
        title: { zh: "6. 隐私、变更、责任限制和争议", en: "6. Privacy, changes, liability, and disputes" },
        items: [
          { zh: "我们会按照官网隐私政策处理您的个人信息和相关数据", en: "We process personal information and related data according to the website Privacy Policy" },
          { zh: "我们可能根据业务调整、技术升级、合规要求、安全风险或第三方服务变化调整官网内容、服务能力、套餐权益或页面结构", en: "We may adjust website content, capabilities, plan benefits, or page structure for business, technical, compliance, security, or third-party changes" },
          { zh: "我们会尽量保持服务稳定，但不保证官网或服务在任何时间、地区、设备或网络环境下均不中断、无错误或满足特定预期", en: "We try to keep services stable but do not guarantee uninterrupted, error-free, or expectation-matching service in every time, region, device, or network" },
          { zh: "本条款适用中华人民共和国法律，争议优先友好协商，协商不成按适用法律处理", en: "These terms are governed by the laws of China. Disputes should first be negotiated and then handled under applicable law" },
        ],
      },
      {
        id: "service-usage",
        title: { zh: "7. 第三方服务和合规使用", en: "7. Third-party services and compliant use" },
        items: [
          { zh: "官网可能展示或接入第三方云服务、支付、短信、邮件、客服、统计分析、地图、企业服务咨询、资质材料协助等能力；具体服务范围、费用、交付条件和责任边界，以订单、合同、平台页面或第三方规则为准", en: "The website may display or integrate third-party cloud, payment, SMS, email, support, analytics, map, enterprise consultation, and qualification material assistance capabilities. Service scope, fees, delivery terms, and responsibility boundaries are subject to orders, contracts, platform pages, or third-party rules" },
          { zh: "xiaoone 仅在合法合规范围内提供信息展示、流程协助、技术接入或客服转派，不承诺代替第三方完成审批、开通、付款、结算或监管义务", en: "xiaoone provides information display, process assistance, technical integration, or support handoff only within lawful and compliant boundaries, and does not undertake third-party approval, activation, payment, settlement, or regulatory obligations on your behalf" },
          { zh: "用户应遵守中华人民共和国法律法规，不得利用官网、工作站、接口或第三方服务从事违法违规、侵权、欺诈、恶意营销、破坏网络安全或损害他人合法权益的行为", en: "Users must comply with the laws and regulations of the People's Republic of China and may not use the website, workspace, APIs, or third-party services for illegal, infringing, fraudulent, malicious marketing, cybersecurity-damaging, or rights-harming activities" },
          { zh: "涉及实名、企业资质、授权材料、发票、合同、支付或数据处理的服务，我们将按最小必要原则依法核验和处理；未完成必要核验的，相关服务可能无法开通或继续使用", en: "For real-name, business qualification, authorization materials, invoices, contracts, payments, or data-processing services, we will verify and process information lawfully under data minimization. Services may be unavailable or suspended if required verification is incomplete" },
        ],
      },
    ],
  },
  refund: {
    eyebrow: { zh: "退款与售后", en: "Refunds and After-sales" },
    title: { zh: "xiaoone 官网退款与售后说明", en: "xiaoone Website Refund and After-sales Policy" },
    summary: {
      zh: "本说明适用于官网侧和 XiaoOne 智能工作站订阅服务，不写入非官网侧产品的专属售后规则",
      en: "This policy applies to website-side and XiaoOne workspace subscriptions, excluding product-specific after-sales rules outside the website",
    },
    sections: [
      {
        title: { zh: "1. 适用服务、开通与生效", en: "1. Applicable services and activation" },
        items: [
          { zh: "适用于官网展示并通过官网、订单、合同或客服确认购买的标准订阅套餐和相关服务", en: "Applies to standard subscription plans and related services purchased through the website, order, contract, or support confirmation" },
          { zh: "套餐购买后按订单或平台确认信息开通，生效时间以实际配置完成时间为准", en: "Plans activate based on order or platform confirmation, with effective time based on actual configuration completion" },
          { zh: "第三方渠道、企业服务咨询、代办、定制交付和人工服务可能有独立计费和售后规则", en: "Third-party channels, enterprise consultation, agency, custom delivery, and manual services may have separate billing and support rules" },
        ],
      },
      {
        title: { zh: "2. 可申请退款的情形", en: "2. Refundable cases" },
        items: [
          { zh: "标准套餐已付款但尚未开通，且未产生资源消耗、人工服务或第三方费用", en: "A standard plan was paid but not activated, with no resource usage, manual service, or third-party fee incurred" },
          { zh: "因系统原因长期无法开通或核心服务无法使用，且在合理修复期限内无法恢复", en: "System issues prevent activation or core use for an extended period and cannot be restored within a reasonable time" },
          { zh: "订单、合同或支付确认页明确约定可退款条件且用户符合条件", en: "The order, contract, or payment confirmation clearly states refundable conditions and the user qualifies" },
        ],
      },
      {
        title: { zh: "3. 原则上不支持无理由退款的情形", en: "3. Usually non-refundable cases" },
        items: [
          { zh: "服务已正常开通并实际使用，或已产生 AI 用量、短信、渠道、云资源、接口调用等成本", en: "Service has been activated and used, or AI usage, SMS, channel, cloud, API, or similar costs were incurred" },
          { zh: "第三方服务商、渠道、资质申请、企业定制服务或人工服务已开始执行", en: "Third-party providers, channels, qualification applications, enterprise customization, or manual services have started" },
          { zh: "因用户资料不完整、不真实、未按要求配合或违反规则导致无法继续服务", en: "Service cannot continue because user materials are incomplete, untrue, non-cooperative, or rule-violating" },
        ],
      },
      {
        title: { zh: "4. 服务期补偿、第三方费用和定制服务", en: "4. Service compensation, third-party fees, and custom work" },
        items: [
          { zh: "因系统故障影响使用时，我们可根据影响范围提供服务期延长、补偿额度或其他合理安排", en: "For system faults affecting use, we may provide service extension, compensation quota, or other reasonable arrangements" },
          { zh: "第三方服务费用、服务商扣费、通道费、支付手续费和已发生外部成本，通常无法退回", en: "Third-party fees, provider deductions, channel fees, payment fees, and incurred external costs are usually non-refundable" },
          { zh: "企业定制、人工配置、专项交付和咨询服务按订单、合同或双方确认的规则处理", en: "Enterprise customization, manual configuration, special delivery, and consulting follow order, contract, or confirmed rules" },
        ],
      },
      {
        title: { zh: "5. 申请方式、处理时效和退款路径", en: "5. Request method, timeline, and refund path" },
        items: [
          { zh: "请通过 support@xiaoone.cn 提交订单信息、付款凭证、退款原因、联系方式和必要说明材料", en: "Submit order information, payment proof, refund reason, contact details, and required materials to support@xiaoone.cn" },
          { zh: "我们会在收到完整材料后尽快核验，具体处理时效以支付渠道、订单、合同或争议情况为准", en: "We will verify as soon as complete materials are received. Timing depends on payment channel, order, contract, or dispute status" },
          { zh: "退款原则上按原支付路径退回；如涉及手续费、发票、合同或对账问题，需要先完成必要处理", en: "Refunds usually return through the original payment path. Fees, invoices, contracts, or reconciliation may need handling first" },
        ],
      },
      {
        title: { zh: "6. 滥用、争议和说明更新", en: "6. Abuse, disputes, and updates" },
        items: [
          { zh: "如存在恶意下单、异常退款、滥用资源、刷量、攻击、欺诈或违反服务条款行为，我们有权拒绝退款或暂停服务", en: "For malicious orders, abnormal refunds, resource abuse, traffic manipulation, attacks, fraud, or Terms violations, we may refuse refunds or suspend service" },
          { zh: "退款争议优先通过 support@xiaoone.cn 沟通解决，必要时按订单、合同和适用法律处理", en: "Refund disputes should first be handled through support@xiaoone.cn and, if needed, according to order, contract, and applicable law" },
          { zh: "本说明可能根据服务内容、计费方式、支付渠道、第三方服务或法律法规更新", en: "This policy may be updated for service, billing, payment channel, third-party, or legal changes" },
        ],
      },
    ],
  },
};

function LegalArticle({ kind }: { kind: Exclude<LegalPageKind, "contact" | "compliance"> }) {
  const { t } = useSitePreferences();
  const page = legalPages[kind];

  return (
    <main className="min-h-screen bg-slate-50 px-4 pb-24 pt-32 text-gray-900 dark:bg-slate-950 dark:text-slate-100 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className="mb-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-indigo-100 bg-indigo-50 px-3 py-1 text-sm font-semibold text-indigo-700 dark:border-indigo-400/20 dark:bg-indigo-400/10 dark:text-indigo-200">
            <ShieldCheck size={16} />
            {t(page.eyebrow)}
          </div>
          <h1 className="mt-6 text-4xl font-bold tracking-tight md:text-5xl">{t(page.title)}</h1>
          <p className="mt-5 text-lg leading-8 text-gray-600 dark:text-slate-300">{t(page.summary)}</p>
        </motion.div>

        <article className="space-y-5">
          {page.sections.map((section, index) => (
            <motion.section
              key={section.title.zh}
              id={'id' in section && typeof section.id === 'string' ? section.id : undefined}
              initial={{ opacity: 0, y: 18 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: index * 0.04 }}
              className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/82"
            >
              <div className="mb-5 flex items-center gap-3">
                <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-400/10 dark:text-indigo-200">
                  <FileText size={20} />
                </div>
                <h2 className="text-xl font-bold">{t(section.title)}</h2>
              </div>
              <ul className="space-y-3">
                {section.items.map(item => (
                  <li key={item.zh} className="flex gap-3 text-sm leading-7 text-gray-600 dark:text-slate-300">
                    <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-indigo-500 dark:bg-indigo-300" />
                    <span>{t(item)}</span>
                  </li>
                ))}
              </ul>
            </motion.section>
          ))}
        </article>
      </div>
    </main>
  );
}

function ContactPage() {
  const { t } = useSitePreferences();
  const [searchParams] = useSearchParams();
  const [status, setStatus] = useState<"idle" | "ready">("idle");
  const subject = useMemo(() => encodeURIComponent("xiaoone 官网咨询"), []);
  const initialIntent = searchParams.get("intent") ?? "";

  function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const body = [
      `姓名：${formData.get("name") ?? ""}`,
      `邮箱：${formData.get("email") ?? ""}`,
      `电话：${formData.get("phone") ?? ""}`,
      `公司名称：${formData.get("company") ?? ""}`,
      "",
      `留言内容：${formData.get("message") ?? ""}`,
    ].join("\n");
    window.location.href = `mailto:${supportEmail}?subject=${subject}&body=${encodeURIComponent(body)}`;
    setStatus("ready");
  }

  return (
    <main className="min-h-screen bg-slate-50 px-4 pb-24 pt-32 text-gray-900 dark:bg-slate-950 dark:text-slate-100 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-6xl">
        <div className="mb-10 max-w-3xl">
          <div className="mb-5 inline-flex items-center gap-2 rounded-full border border-cyan-100 bg-cyan-50 px-3 py-1 text-sm font-semibold text-cyan-700 dark:border-cyan-400/20 dark:bg-cyan-400/10 dark:text-cyan-200">
            <Mail size={16} />
            {t({ zh: "联系我们", en: "Contact us" })}
          </div>
          <h1 className="text-4xl font-bold tracking-tight md:text-5xl">{t({ zh: "联系 xiaoone", en: "Contact xiaoone" })}</h1>
          <p className="mt-5 text-lg leading-8 text-gray-600 dark:text-slate-300">
            {t({
              zh: "销售咨询、售后支持、隐私请求和合规事项都统一进入 support 邮箱，由客服内部转派处理",
              en: "Sales inquiries, support, privacy requests, and compliance matters all enter the support mailbox and are routed internally",
            })}
          </p>
        </div>

        <div className="grid gap-8 lg:grid-cols-[360px_1fr]">
          <aside className="space-y-5">
            <div className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/80">
              <h2 className="mb-5 flex items-center gap-2 text-lg font-bold"><Phone size={18} />{t({ zh: "联系信息", en: "Contact details" })}</h2>
              <div className="space-y-4 text-sm leading-7 text-gray-600 dark:text-slate-300">
                <p><strong className="text-gray-900 dark:text-slate-100">{t({ zh: "客服邮箱", en: "Support email" })}：</strong><a href={`mailto:${supportEmail}`} className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">{supportEmail}</a></p>
                <p><strong className="text-gray-900 dark:text-slate-100">{t({ zh: "客服电话", en: "Support phone" })}：</strong><a href="tel:17307404063" className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">17307404063</a></p>
                <p>{t({ zh: "适合咨询套餐购买、开通范围、发票、合同、售后支持、隐私数据请求、SDK 和 API 接入", en: "Use this for plan purchase, activation scope, invoice, contracts, support, privacy requests, SDK, and API integration" })}</p>
              </div>
            </div>

            <div className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/80">
              <h2 className="mb-5 flex items-center gap-2 text-lg font-bold"><Building2 size={18} />{t({ zh: "公司信息", en: "Company information" })}</h2>
              <dl className="space-y-4 text-sm">
                {companyInfo.map(([label, value]) => (
                  <div key={label.zh}>
                    <dt className="text-gray-500 dark:text-slate-400">{t(label)}</dt>
                    <dd className="mt-1 font-semibold leading-6 text-gray-900 dark:text-slate-100">{t(value)}</dd>
                  </div>
                ))}
              </dl>
              <div className="mt-5 flex items-start gap-2 rounded-xl bg-slate-50 p-3 text-xs leading-5 text-gray-500 dark:bg-slate-800 dark:text-slate-400">
                <MapPin size={14} className="mt-0.5 flex-shrink-0 text-indigo-500" />
                {t({ zh: "全站页脚仅展示精简注册地址，完整地址在本页保留", en: "The footer shows a shortened address; the full address remains here" })}
              </div>
            </div>
          </aside>

          <form onSubmit={submit} className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/80 sm:p-8">
            <h2 className="mb-2 text-2xl font-bold">{t({ zh: "发送消息", en: "Send a message" })}</h2>
            <p className="mb-6 text-sm leading-7 text-gray-600 dark:text-slate-300">
              {t({
                zh: "当前官网未接入后端邮件发送接口，提交后会打开您的邮件客户端并填充收件人与内容，不会在前端暴露邮箱密钥",
                en: "The site has not connected a backend mail endpoint yet. Submission opens your mail client with recipient and content filled, without exposing mail credentials in the frontend",
              })}
            </p>
            <div className="grid gap-4 sm:grid-cols-2">
              <label className="text-sm font-semibold">
                {t({ zh: "姓名", en: "Name" })} *
                <input required name="name" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition-colors focus:border-indigo-400 dark:border-white/10 dark:bg-slate-800 dark:text-slate-100" />
              </label>
              <label className="text-sm font-semibold">
                {t({ zh: "邮箱", en: "Email" })} *
                <input required type="email" name="email" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition-colors focus:border-indigo-400 dark:border-white/10 dark:bg-slate-800 dark:text-slate-100" />
              </label>
              <label className="text-sm font-semibold">
                {t({ zh: "电话", en: "Phone" })}
                <input name="phone" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition-colors focus:border-indigo-400 dark:border-white/10 dark:bg-slate-800 dark:text-slate-100" />
              </label>
              <label className="text-sm font-semibold">
                {t({ zh: "公司名称", en: "Company" })}
                <input name="company" className="mt-2 w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition-colors focus:border-indigo-400 dark:border-white/10 dark:bg-slate-800 dark:text-slate-100" />
              </label>
              <label className="sm:col-span-2 text-sm font-semibold">
                {t({ zh: "留言内容", en: "Message" })} *
                <textarea required name="message" rows={6} defaultValue={initialIntent} className="mt-2 w-full resize-none rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm text-gray-900 outline-none transition-colors focus:border-indigo-400 dark:border-white/10 dark:bg-slate-800 dark:text-slate-100" />
              </label>
            </div>
            <label className="mt-5 flex items-start gap-3 text-sm leading-6 text-gray-600 dark:text-slate-300">
              <input required type="checkbox" className="mt-1 h-4 w-4 rounded border-slate-300 text-indigo-600" />
              <span>{t({ zh: "我同意按隐私政策处理上述信息，用于回复本次咨询", en: "I agree that the information above may be processed under the Privacy Policy to respond to this inquiry" })}</span>
            </label>
            <button className="mt-6 inline-flex items-center justify-center gap-2 rounded-xl bg-indigo-600 px-5 py-3 text-sm font-bold text-white transition-colors hover:bg-indigo-500">
              <Send size={16} />
              {t({ zh: "打开邮件客户端发送", en: "Open mail client to send" })}
            </button>
            {status === "ready" && (
              <p className="mt-4 text-sm font-semibold text-emerald-600 dark:text-emerald-300">
                {t({ zh: "已为您填充邮件内容，请在邮件客户端确认发送", en: "The email has been prepared. Please confirm sending in your mail client" })}
              </p>
            )}
          </form>
        </div>
      </div>
    </main>
  );
}

function ComplaintPage() {
  const { t } = useSitePreferences();
  const subject = useMemo(() => encodeURIComponent("xiaoone 投诉举报 / Compliance Report"), []);
  const reportScopes: LocalizedCopy[] = [
    { zh: "违法、违规、欺诈、谣言、危害国家安全或社会公共利益的内容与行为", en: "Illegal, regulatory-violating, fraudulent, rumor-spreading, or public-interest-harming content and behavior" },
    { zh: "色情、暴力、赌博、毒品、自杀自残、未成年人不宜的有害信息", en: "Pornography, violence, gambling, drugs, self-harm, or content harmful to minors" },
    { zh: "侵犯个人信息、隐私、肖像、名誉、知识产权或商业秘密的内容", en: "Content infringing personal information, privacy, portrait, reputation, intellectual property, or trade secrets" },
    { zh: "钓鱼、诈骗、恶意营销、垃圾信息、刷量、虚假交易等扰乱平台秩序的行为", en: "Phishing, fraud, malicious marketing, spam, traffic manipulation, fake transactions, and other order-disrupting behavior" },
    { zh: "未经授权访问、攻击、滥用接口、绕过限流、扫描漏洞等危害系统安全的行为", en: "Unauthorized access, attacks, API abuse, rate-limit evasion, vulnerability scanning, and other behavior threatening system security" },
    { zh: "怀疑账号被盗用、密码泄露、数据被违规导出、子账号越权等安全事件", en: "Suspected account takeover, password leak, unauthorized data export, sub-account privilege escalation, and similar security events" },
  ];
  const materials: LocalizedCopy[] = [
    { zh: "举报内容的具体描述：发生时间、涉及账号、商户或店铺名称、相关链接或截图", en: "Detailed description of the report: time of occurrence, accounts involved, merchant or store name, relevant links or screenshots" },
    { zh: "您的真实身份与联系方式：姓名、邮箱、电话，便于核实与反馈处理结果", en: "Your real identity and contact details: name, email, phone, so we can verify and reply with the handling result" },
    { zh: "权利证明或证据材料（如涉及侵权举报）：身份证、营业执照、商标证书、著作权登记或其他权属证明", en: "Rights proof or evidence (for infringement reports): ID, business license, trademark certificate, copyright registration, or other ownership proof" },
    { zh: "如涉及紧急违法有害信息或网络安全事件，请在邮件主题中标注「紧急」并同时拨打客服电话", en: "For urgent illegal/harmful information or cybersecurity events, mark the email subject as URGENT and also call the support phone" },
  ];
  const flow: LocalizedCopy[] = [
    { zh: "受理：收到举报后 1 个工作日内回执确认，分配处理人", en: "Intake: confirm receipt within 1 business day and assign a handler" },
    { zh: "核查：依据规则、留存数据、内容快照、操作日志综合判定", en: "Investigation: assess by rules, retained data, content snapshots, and operation logs" },
    { zh: "处置：提醒整改、隐藏/删除、暂停自动回复、限制账号或商户功能、封禁、移送主管部门，根据严重程度采取相应措施", en: "Action: warning, hide/remove, suspend auto-reply, restrict account or merchant features, ban, refer to authorities, based on severity" },
    { zh: "反馈：一般问题 7 个工作日内反馈处理结果；涉及紧急违法有害信息，24 小时内启动初步处置并反馈进度", en: "Feedback: general issues replied within 7 business days; urgent illegal/harmful information triggers initial handling within 24 hours with progress reply" },
    { zh: "复核与申诉：处置对象可在 15 个工作日内申诉，平台合规复核并答复结果", en: "Review and appeal: subjects of action may appeal within 15 business days, with compliance review and reply" },
  ];

  const body = useMemo(() => encodeURIComponent([
    "【举报对象】：",
    "【涉及账号 / 商户 / 店铺】：",
    "【发生时间】：",
    "【相关链接或截图】：",
    "【举报理由】：",
    "【您的姓名 / 邮箱 / 电话】：",
    "",
    "（如涉及紧急违法有害信息或安全事件，请在主题中加 [紧急]）",
  ].join("\n")), []);

  return (
    <main className="min-h-screen bg-slate-50 px-4 pb-24 pt-32 text-gray-900 dark:bg-slate-950 dark:text-slate-100 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-4xl">
        <motion.div initial={{ opacity: 0, y: 18 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.45 }} className="mb-10">
          <div className="inline-flex items-center gap-2 rounded-full border border-rose-100 bg-rose-50 px-3 py-1 text-sm font-semibold text-rose-700 dark:border-rose-400/20 dark:bg-rose-400/10 dark:text-rose-200">
            <Flag size={16} />
            {t({ zh: "投诉举报 / 合规反馈", en: "Report and Compliance Feedback" })}
          </div>
          <h1 className="mt-6 text-4xl font-bold tracking-tight md:text-5xl">
            {t({ zh: "投诉举报与违法信息处置", en: "Reporting and Illegal Content Handling" })}
          </h1>
          <p className="mt-5 text-lg leading-8 text-gray-600 dark:text-slate-300">
            {t({
              zh: "我们为用户、商户和外部公众提供专门的投诉举报与合规反馈通道，依法依规受理、核查、处置并反馈结果",
              en: "We provide a dedicated channel for users, merchants, and the public to submit reports and compliance feedback. Submissions are received, investigated, handled, and replied to in line with applicable laws and rules",
            })}
          </p>
        </motion.div>

        <div className="mb-6 grid gap-4 md:grid-cols-2">
          <a
            href={`mailto:${complianceEmail}?subject=${subject}&body=${body}`}
            className="group rounded-2xl border border-rose-200 bg-white/90 p-6 shadow-sm transition-colors hover:border-rose-400 dark:border-rose-400/20 dark:bg-slate-900/82 dark:hover:border-rose-300"
          >
            <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-rose-700 dark:text-rose-200">
              <Mail size={16} />
              {t({ zh: "专用邮箱（建议优先使用）", en: "Dedicated email (recommended)" })}
            </div>
            <p className="text-lg font-bold text-gray-900 dark:text-slate-100">{complianceEmail}</p>
            <p className="mt-3 text-sm leading-6 text-gray-600 dark:text-slate-300">
              {t({
                zh: "点击会打开邮件客户端并自动填充举报模板；如邮箱暂不可用，可使用下方备用通道",
                en: "Clicking opens your mail client with a prefilled report template. If this mailbox is temporarily unavailable, use the backup channels below",
              })}
            </p>
          </a>
          <div className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/82">
            <div className="mb-3 flex items-center gap-2 text-sm font-semibold text-gray-700 dark:text-slate-200">
              <Phone size={16} />
              {t({ zh: "备用通道", en: "Backup channels" })}
            </div>
            <p className="text-sm leading-7 text-gray-600 dark:text-slate-300">
              <strong className="text-gray-900 dark:text-slate-100">{t({ zh: "客服电话", en: "Support phone" })}：</strong>
              <a href={`tel:${supportPhone}`} className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">{supportPhone}</a>
            </p>
            <p className="text-sm leading-7 text-gray-600 dark:text-slate-300">
              <strong className="text-gray-900 dark:text-slate-100">{t({ zh: "客服邮箱", en: "Support email" })}：</strong>
              <a href={`mailto:${supportEmail}`} className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">{supportEmail}</a>
            </p>
            <p className="mt-3 text-xs leading-5 text-gray-500 dark:text-slate-400">
              {t({
                zh: "通过备用通道提交的投诉举报会由客服按合规流程内部转派，处理时限与专用邮箱一致",
                en: "Reports submitted via backup channels are routed by support to the compliance flow with the same processing timeline as the dedicated mailbox",
              })}
            </p>
          </div>
        </div>

        <article className="space-y-5">
          <motion.section
            initial={{ opacity: 0, y: 18 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.04 }}
            className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/82"
          >
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-rose-50 text-rose-600 dark:bg-rose-400/10 dark:text-rose-200">
                <AlertTriangle size={20} />
              </div>
              <h2 className="text-xl font-bold">{t({ zh: "受理范围", en: "Reportable scope" })}</h2>
            </div>
            <ul className="space-y-3">
              {reportScopes.map(item => (
                <li key={item.zh} className="flex gap-3 text-sm leading-7 text-gray-600 dark:text-slate-300">
                  <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-rose-500 dark:bg-rose-300" />
                  <span>{t(item)}</span>
                </li>
              ))}
            </ul>
          </motion.section>

          <motion.section
            initial={{ opacity: 0, y: 18 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.08 }}
            className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/82"
          >
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-indigo-50 text-indigo-600 dark:bg-indigo-400/10 dark:text-indigo-200">
                <FileText size={20} />
              </div>
              <h2 className="text-xl font-bold">{t({ zh: "举报所需材料", en: "Required materials" })}</h2>
            </div>
            <ul className="space-y-3">
              {materials.map(item => (
                <li key={item.zh} className="flex gap-3 text-sm leading-7 text-gray-600 dark:text-slate-300">
                  <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-indigo-500 dark:bg-indigo-300" />
                  <span>{t(item)}</span>
                </li>
              ))}
            </ul>
          </motion.section>

          <motion.section
            initial={{ opacity: 0, y: 18 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.12 }}
            className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/82"
          >
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-50 text-emerald-600 dark:bg-emerald-400/10 dark:text-emerald-200">
                <Clock size={20} />
              </div>
              <h2 className="text-xl font-bold">{t({ zh: "受理与反馈时限", en: "Handling timeline" })}</h2>
            </div>
            <ul className="space-y-3">
              {flow.map(item => (
                <li key={item.zh} className="flex gap-3 text-sm leading-7 text-gray-600 dark:text-slate-300">
                  <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-emerald-500 dark:bg-emerald-300" />
                  <span>{t(item)}</span>
                </li>
              ))}
            </ul>
          </motion.section>

          <motion.section
            initial={{ opacity: 0, y: 18 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ delay: 0.16 }}
            className="rounded-2xl border border-slate-200 bg-white/90 p-6 shadow-sm dark:border-white/10 dark:bg-slate-900/82"
          >
            <div className="mb-5 flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-50 text-amber-600 dark:bg-amber-400/10 dark:text-amber-200">
                <ShieldCheck size={20} />
              </div>
              <h2 className="text-xl font-bold">{t({ zh: "我们的承诺", en: "Our commitments" })}</h2>
            </div>
            <ul className="space-y-3 text-sm leading-7 text-gray-600 dark:text-slate-300">
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-amber-500 dark:bg-amber-300" />
                <span>{t({ zh: "对举报人身份、联系方式和材料内容严格保密，仅在核查、处置和监管协助所需范围内使用", en: "Reporter identity, contact details, and submitted materials are kept strictly confidential and used only within the scope necessary for investigation, handling, and regulatory cooperation" })}</span>
              </li>
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-amber-500 dark:bg-amber-300" />
                <span>{t({ zh: "处置依据公开规则、留存证据和操作日志，可追溯、可复核，避免随意封禁", en: "Actions follow public rules, retained evidence, and operation logs to ensure traceability and review, avoiding arbitrary bans" })}</span>
              </li>
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-amber-500 dark:bg-amber-300" />
                <span>{t({ zh: "如举报内容涉及违法犯罪线索，我们将依法依规配合公安、网信、通信管理等主管部门工作", en: "If reports involve criminal leads, we cooperate with public security, cyberspace administration, telecommunications authorities, and other competent agencies in line with the law" })}</span>
              </li>
              <li className="flex gap-3">
                <span className="mt-2 h-1.5 w-1.5 flex-shrink-0 rounded-full bg-amber-500 dark:bg-amber-300" />
                <span>{t({ zh: "请勿提交虚假、恶意或重复举报；对于伪造证据、滥用举报、攻击平台或他人合法权益的行为，我们有权拒绝处理并保留追究责任的权利", en: "Do not submit false, malicious, or duplicate reports. We may reject handling and reserve the right to pursue liability for forged evidence, abuse of reporting, or attacks on the platform or others' lawful rights" })}</span>
              </li>
            </ul>
          </motion.section>
        </article>

        <div className="mt-10 rounded-2xl border border-slate-200 bg-white/90 p-6 text-sm leading-7 text-gray-600 shadow-sm dark:border-white/10 dark:bg-slate-900/82 dark:text-slate-300">
          <p>
            {t({
              zh: "如您希望了解我们在日志留存、个人信息保护和监管协助方面的内部制度，请前往",
              en: "To learn about our internal policies for log retention, personal information protection, and regulatory cooperation, see ",
            })}
            <Link to="/privacy" className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">
              {t({ zh: "隐私政策", en: "Privacy Policy" })}
            </Link>
            {t({ zh: "、", en: ", " })}
            <Link to="/terms" className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">
              {t({ zh: "用户协议", en: "User Agreement" })}
            </Link>
            {t({ zh: "与", en: ", and " })}
            <Link to="/refund-policy" className="text-indigo-600 hover:text-indigo-500 dark:text-indigo-300">
              {t({ zh: "退款与售后", en: "Refund & After-sales" })}
            </Link>
            {t({ zh: "。", en: "." })}
          </p>
        </div>
      </div>
    </main>
  );
}

export function LegalPage({ kind }: { kind: LegalPageKind }) {
  if (kind === "contact")
    return <ContactPage />;
  if (kind === "compliance")
    return <ComplaintPage />;

  return <LegalArticle kind={kind} />;
}
